import React from 'react';
import { ShoppingCart, Stethoscope, Landmark, Factory, Globe } from 'lucide-react';
import { VerticalType, VerticalConfig } from './types';

export const IDLE_TIMEOUT = 120000; // 2 minutes

export const VERTICALS: VerticalConfig[] = [
  {
    id: 'agentic-governance',
    title: 'Agentic Governance',
    icon: 'shield-check',
    color: 'bg-indigo-600',
    externalUrl: 'https://agentic-vendor-governance-platform-956266717219.us-west4.run.app',
    pitch: {
      problem: 'Enterprises lack real-time oversight and control over autonomous AI agents.',
      solution: 'Policy-aware agent orchestration with continuous compliance and auditability.',
      talkingPoints: [
        'Real-time policy enforcement across AI agents.',
        'Explainable decision trails for governance and audits.',
        'Centralized control for multi-agent ecosystems.'
      ]
    }
  },
  {
    id: 'shelflogic-autonomous-merchandising',
    title: 'ShelfLogic AI',
    icon: 'layers',
    color: 'bg-emerald-600',
    externalUrl: 'https://shelflogic-ai-inventory-optimization-956266717219.us-west4.run.app',
    pitch: {
      problem: 'Merchandising decisions are slow, manual, and disconnected from real-time demand.',
      solution: 'Autonomous AI agents continuously optimize assortment, pricing, and placement.',
      talkingPoints: [
        'Self-optimizing assortments driven by demand signals.',
        'Autonomous price and promotion adjustments.',
        'Closed-loop execution from insight to shelf.'
      ]
    }
  },
  {
    id: 'contract-intelligence',
    title: 'Contract Intelligence',
    icon: 'file-text',
    color: 'bg-sky-600',
    externalUrl: 'https://contract-intelligence-platform-956266717219.us-west4.run.app',
    pitch: {
      problem: 'Critical contract risks and obligations are hidden in unstructured documents.',
      solution: 'AI-powered contract analysis with risk scoring and obligation tracking.',
      talkingPoints: [
        'Automated clause extraction and classification.',
        'Early detection of financial and compliance risks.',
        'Natural language contract search and summarization.'
      ]
    }
  },
  {
    id: 'sentinel-ai',
    title: 'Sentinel AI',
    icon: 'shield-alert',
    color: 'bg-red-700',
    externalUrl: 'https://sentinel-ai-autonomous-risk-assurance-956266717219.us-west4.run.app',
    pitch: {
      problem: 'Traditional controls fail to detect complex, fast-moving enterprise risks.',
      solution: 'Autonomous AI agents monitor, detect, and respond to risk in real time.',
      talkingPoints: [
        'Continuous risk monitoring across systems.',
        'Autonomous incident triage and escalation.',
        'Explainable AI-driven assurance decisions.'
      ]
    }
  },
  {
    id: 'supply-chain-logistics',
    title: 'Supply Chain and Logistics',
    icon: 'truck',
    color: 'bg-orange-500',
    externalUrl: 'https://supply-chain-and-logistics-demo-956266717219.us-west4.run.app',
    pitch: {
      problem: 'Global supply chains suffer from poor visibility and slow response to disruptions.',
      solution: 'AI-driven logistics orchestration with predictive and prescriptive insights.',
      talkingPoints: [
        'End-to-end shipment visibility in real time.',
        'Predictive disruption detection and mitigation.',
        'Optimized routing, inventory, and fulfillment.'
      ]
    }
  },
  {
    id: 'cloud-compliance',
    title: 'Guardian AI Compliance',
    icon: 'clipboard-check',
    color: 'bg-teal-600',
    externalUrl: 'https://cloud-compliance-agentic-suite-v2-956266717219.us-west4.run.app',
    pitch: {
      problem: 'Regulatory compliance is manual, reactive, and prone to human error.',
      solution: 'Agentic suite for continuous monitoring, audit generation, and regulatory alignment.',
      talkingPoints: [
        'Real-time risk scoring across multiple frameworks (Banking, Privacy).',
        'Immutable, zero-cost supervisory audit trails generated by agents.',
        'Interactive compliance expert chat and workflow simulation.'
      ]
    }
  },
  {
    id: 'contractinel-ai',
    title: 'Contractinel AI',
    icon: 'clipboard-check',
    color: 'bg-teal-600',
    externalUrl: 'https://contractintel-ai-956266717219.us-west4.run.app',
    pitch: {
      problem: 'Organizations lack real-time visibility into contractual risk, compliance exposure, and review inefficiencies.',
      solution: 'AI-powered contract analysis platform delivering real-time risk intelligence, automated reviews, and compliance insights.',
      talkingPoints: [
        'Real-time detection of high-risk clauses and compliance gaps.',
        'Average contract review time reduced to under 10 minutes.',
        'Automated risk scoring across jurisdictions and contract categories.'
      ]
    }
  },
  {
    id: 'buildintel',
    title: 'BuildIntel',
    icon: 'shield-check',
    color: 'bg-navy',
    externalUrl: 'https://buildintel-construction-ai-platform-956266717219.us-west4.run.app',
    pitch: {
      problem: 'Large construction portfolios lack real-time oversight across projects, risks, workforce, and cost variance—leading to delayed decisions and escalating delivery risk.',
      solution: 'An agentic governance dashboard that provides real-time portfolio intelligence, continuous risk monitoring, and proactive AI agent alerts across all active projects.',
      talkingPoints: [
        'Unified real-time visibility across projects, risks, and workforce in a single portfolio view.',
        'Autonomous agents surface critical risk alerts and escalate issues before they impact delivery.',
        'Continuous tracking of forecast variance and progress to improve governance and execution control.'
      ]
    }
  },
];

export const MOCK_DATA = {
  retail: {
    inventory: [
      { id: '1', item: 'Cloud Runner Z', stock: 45, status: 'Healthy' },
      { id: '2', item: 'Pixel Buds Pro', stock: 12, status: 'Low Stock' },
      { id: '3', item: 'Chromecast Ultra', stock: 89, status: 'Healthy' },
      { id: '4', item: 'Nest Cam IQ', stock: 5, status: 'Critical' }
    ],
    salesChart: [
      { name: 'Mon', sales: 4000 },
      { name: 'Tue', sales: 3000 },
      { name: 'Wed', sales: 5000 },
      { name: 'Thu', sales: 2780 },
      { name: 'Fri', sales: 1890 },
      { name: 'Sat', sales: 2390 },
      { name: 'Sun', sales: 3490 }
    ]
  },
  healthcare: {
    patients: [
      { id: '101', name: 'Alice Smith', age: 45, condition: 'Stable' },
      { id: '102', name: 'Bob Johnson', age: 67, condition: 'Monitoring' },
      { id: '103', name: 'Charlie Davis', age: 32, condition: 'Critical' }
    ]
  },
  fintech: {
    transactions: [
      { id: 'TX-998', amount: 1250.00, risk: 'Low', status: 'Approved' },
      { id: 'TX-999', amount: 45000.00, risk: 'High', status: 'Flagged' },
      { id: 'TX-1000', amount: 89.99, risk: 'Low', status: 'Approved' }
    ]
  }
};
