substitutions:
  _REGION: us-west4
  _AR_REPO: gcp-demos
  _SERVICE: cloud-compliance-agentic-suite-v2
  _DEMO_DIR: cloud-compliance-agentic-suite-v2
  _PROJECT_ID: p-s-gcu-na-marketing-bd5y-1
  _IAP_GROUP: gcu_demos_temp_group@endava.com

availableSecrets:
  secretManager:
    - versionName: projects/${_PROJECT_ID}/secrets/GEMINI_API_KEY/versions/latest
      env: GEMINI_API_KEY

options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # 1. Build de la imagen (requiere bash para expandir el secreto)
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker build \
          --build-arg "GEMINI_API_KEY=$$GEMINI_API_KEY" \
          -f ${_DEMO_DIR}/Dockerfile \
          -t ${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_AR_REPO}/${_SERVICE}:${SHORT_SHA} \
          ${_DEMO_DIR}
    secretEnv: ['GEMINI_API_KEY']

  # 2. Push de la imagen
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_AR_REPO}/${_SERVICE}:${SHORT_SHA}'

  # 3. Deploy a Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Deploy'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud beta run deploy ${_SERVICE} \
          --image=${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_AR_REPO}/${_SERVICE}:${SHORT_SHA} \
          --region=${_REGION} \
          --platform=managed \
          --no-allow-unauthenticated \
          --iap \
          --port=80 \
          --set-env-vars="GEMINI_API_KEY=$$GEMINI_API_KEY" \
          --min-instances 1

    secretEnv: ['GEMINI_API_KEY']

  # 4. Allow access to the IAP group
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'IAP-Access'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud beta iap web add-iam-policy-binding \
          --member=group:${_IAP_GROUP} \
          --role=roles/iap.httpsResourceAccessor \
          --region=${_REGION} \
          --resource-type=cloud-run \
          --service=${_SERVICE}

images:
  - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_AR_REPO}/${_SERVICE}:${SHORT_SHA}'
 